import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";


export const metadata: Metadata = {
  title: "MoDarly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/modarly.jpeg" />
      </head>
      <body
        className={`antialiased h-dvh flex max-md:flex-col`}
      >
        <Sidebar />
        {children}
      </body>
    </html>
  );
}